# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns: 
          - "*"
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
    groups:
      terraform-modules:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/workshop-user-registration"
    schedule:
      interval: "daily"
    groups:
      npm-packages:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directories:
      - "/docker"
      - "/workshop-user-registration"
    schedule:
      interval: "daily"
    groups:
      docker-images:
        patterns:
          - "*"